# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class SomeStructStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SomeFunction = channel.unary_unary(
        '/api.SomeStruct/SomeFunction',
        request_serializer=test__pb2.MSG1.SerializeToString,
        response_deserializer=test__pb2.MSG1.FromString,
        )


class SomeStructServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SomeFunction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SomeStructServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SomeFunction': grpc.unary_unary_rpc_method_handler(
          servicer.SomeFunction,
          request_deserializer=test__pb2.MSG1.FromString,
          response_serializer=test__pb2.MSG1.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.SomeStruct', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
