# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x03\x61pi\"\x11\n\x04MSG1\x12\t\n\x01\x41\x18\x01 \x01(\t24\n\nSomeStruct\x12&\n\x0cSomeFunction\x12\t.api.MSG1\x1a\t.api.MSG1\"\x00\x62\x06proto3')
)




_MSG1 = _descriptor.Descriptor(
  name='MSG1',
  full_name='api.MSG1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='api.MSG1.A', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=36,
)

DESCRIPTOR.message_types_by_name['MSG1'] = _MSG1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MSG1 = _reflection.GeneratedProtocolMessageType('MSG1', (_message.Message,), dict(
  DESCRIPTOR = _MSG1,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:api.MSG1)
  ))
_sym_db.RegisterMessage(MSG1)



_SOMESTRUCT = _descriptor.ServiceDescriptor(
  name='SomeStruct',
  full_name='api.SomeStruct',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=38,
  serialized_end=90,
  methods=[
  _descriptor.MethodDescriptor(
    name='SomeFunction',
    full_name='api.SomeStruct.SomeFunction',
    index=0,
    containing_service=None,
    input_type=_MSG1,
    output_type=_MSG1,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOMESTRUCT)

DESCRIPTOR.services_by_name['SomeStruct'] = _SOMESTRUCT

# @@protoc_insertion_point(module_scope)
